/// Data model and comprehensive ISO 4217 list of world currencies
/// with flag icon (emoji & country code), currency code (e.g. IDR),
/// and symbol (e.g. Rp).
class Currency {
  /// ISO 4217 3-letter currency code, e.g. "IDR", "USD".
  final String code;

  /// Currency symbol, e.g. "Rp", "$", "€", "¥".
  final String symbol;

  /// Native currency symbol, e.g. "Rp", "$", "€", "¥", "د.إ".
  final String symbolNative;

  /// English currency name, e.g. "Indonesian Rupiah".
  final String name;

  /// Indonesian currency name, e.g. "Rupiah Indonesia".
  final String nameId;

  /// Flag emoji, e.g. "🇮🇩", "🇺🇸", "🇪🇺".
  final String flag;

  /// ISO 3166-1 alpha-2 country code representing the primary country/region,
  /// e.g. "ID", "US", "EU", "GB". Useful for SVG / PNG flag image lookups.
  final String countryCode;

  /// Number of decimal digits used in standard formatting.
  /// (e.g. 0 for IDR, JPY; 2 for USD, EUR; 3 for KWD, BHD).
  final int decimalDigits;

  const Currency({
    required this.code,
    required this.symbol,
    required this.symbolNative,
    required this.name,
    required this.nameId,
    required this.flag,
    required this.countryCode,
    this.decimalDigits = 2,
  });

  /// Factory from Map / JSON.
  factory Currency.fromJson(Map<String, dynamic> json) {
    return Currency(
      code: json['code'] as String,
      symbol: json['symbol'] as String,
      symbolNative: (json['symbolNative'] ?? json['symbol']) as String,
      name: json['name'] as String,
      nameId: (json['nameId'] ?? json['name']) as String,
      flag: json['flag'] as String,
      countryCode: json['countryCode'] as String,
      decimalDigits: (json['decimalDigits'] as num?)?.toInt() ?? 2,
    );
  }

  /// Converts this currency object to a JSON-compatible Map.
  Map<String, dynamic> toJson() {
    return {
      'code': code,
      'symbol': symbol,
      'symbolNative': symbolNative,
      'name': name,
      'nameId': nameId,
      'flag': flag,
      'countryCode': countryCode,
      'decimalDigits': decimalDigits,
    };
  }

  /// Look up a currency by ISO code (case-insensitive).
  /// Throws [ArgumentError] if the code is not recognized.
  factory Currency.fromCode(String code) {
    final found = maybeFromCode(code);
    if (found == null) {
      throw ArgumentError('Unrecognized currency code: $code');
    }
    return found;
  }

  /// Look up a currency by ISO code (case-insensitive), or null if not found.
  static Currency? maybeFromCode(String? code) {
    if (code == null || code.trim().isEmpty) return null;
    return _currencyMapByCode[code.trim().toUpperCase()];
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Currency &&
          runtimeType == other.runtimeType &&
          code == other.code;

  @override
  int get hashCode => code.hashCode;

  @override
  String toString() => '$flag $code ($symbol) - $name';
}

/// Default currency for this app (Indonesian Rupiah).
const Currency defaultCurrency = Currency(
  code: 'IDR',
  symbol: 'Rp',
  symbolNative: 'Rp',
  name: 'Indonesian Rupiah',
  nameId: 'Rupiah Indonesia',
  flag: '🇮🇩',
  countryCode: 'ID',
  decimalDigits: 0,
);

/// Major currencies commonly used in Southeast Asia and international finance.
final List<Currency> majorCurrencies = List.unmodifiable([
  defaultCurrency,
  const Currency(
    code: 'USD',
    symbol: r'$',
    symbolNative: r'$',
    name: 'US Dollar',
    nameId: 'Dolar Amerika Serikat',
    flag: '🇺🇸',
    countryCode: 'US',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'EUR',
    symbol: '€',
    symbolNative: '€',
    name: 'Euro',
    nameId: 'Euro',
    flag: '🇪🇺',
    countryCode: 'EU',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'SGD',
    symbol: r'S$',
    symbolNative: r'$',
    name: 'Singapore Dollar',
    nameId: 'Dolar Singapura',
    flag: '🇸🇬',
    countryCode: 'SG',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'MYR',
    symbol: 'RM',
    symbolNative: 'RM',
    name: 'Malaysian Ringgit',
    nameId: 'Ringgit Malaysia',
    flag: '🇲🇾',
    countryCode: 'MY',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'JPY',
    symbol: '¥',
    symbolNative: '¥',
    name: 'Japanese Yen',
    nameId: 'Yen Jepang',
    flag: '🇯🇵',
    countryCode: 'JP',
    decimalDigits: 0,
  ),
  const Currency(
    code: 'GBP',
    symbol: '£',
    symbolNative: '£',
    name: 'British Pound',
    nameId: 'Pound Sterling Inggris',
    flag: '🇬🇧',
    countryCode: 'GB',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'AUD',
    symbol: r'A$',
    symbolNative: r'$',
    name: 'Australian Dollar',
    nameId: 'Dolar Australia',
    flag: '🇦🇺',
    countryCode: 'AU',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'CNY',
    symbol: '¥',
    symbolNative: '¥',
    name: 'Chinese Yuan',
    nameId: 'Yuan Tiongkok',
    flag: '🇨🇳',
    countryCode: 'CN',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'KRW',
    symbol: '₩',
    symbolNative: '₩',
    name: 'South Korean Won',
    nameId: 'Won Korea Selatan',
    flag: '🇰🇷',
    countryCode: 'KR',
    decimalDigits: 0,
  ),
  const Currency(
    code: 'SAR',
    symbol: 'SAR',
    symbolNative: '﷼',
    name: 'Saudi Riyal',
    nameId: 'Riyal Arab Saudi',
    flag: '🇸🇦',
    countryCode: 'SA',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'AED',
    symbol: 'AED',
    symbolNative: 'د.إ',
    name: 'UAE Dirham',
    nameId: 'Dirham Uni Emirat Arab',
    flag: '🇦🇪',
    countryCode: 'AE',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'THB',
    symbol: '฿',
    symbolNative: '฿',
    name: 'Thai Baht',
    nameId: 'Baht Thailand',
    flag: '🇹🇭',
    countryCode: 'TH',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'PHP',
    symbol: '₱',
    symbolNative: '₱',
    name: 'Philippine Peso',
    nameId: 'Peso Filipina',
    flag: '🇵🇭',
    countryCode: 'PH',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'VND',
    symbol: '₫',
    symbolNative: '₫',
    name: 'Vietnamese Dong',
    nameId: 'Dong Vietnam',
    flag: '🇻🇳',
    countryCode: 'VN',
    decimalDigits: 0,
  ),
  const Currency(
    code: 'HKD',
    symbol: r'HK$',
    symbolNative: r'$',
    name: 'Hong Kong Dollar',
    nameId: 'Dolar Hong Kong',
    flag: '🇭🇰',
    countryCode: 'HK',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'TWD',
    symbol: r'NT$',
    symbolNative: r'NT$',
    name: 'New Taiwan Dollar',
    nameId: 'Dolar Taiwan Baru',
    flag: '🇹🇼',
    countryCode: 'TW',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'INR',
    symbol: '₹',
    symbolNative: '₹',
    name: 'Indian Rupee',
    nameId: 'Rupee India',
    flag: '🇮🇳',
    countryCode: 'IN',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'CAD',
    symbol: r'C$',
    symbolNative: r'$',
    name: 'Canadian Dollar',
    nameId: 'Dolar Kanada',
    flag: '🇨🇦',
    countryCode: 'CA',
    decimalDigits: 2,
  ),
  const Currency(
    code: 'CHF',
    symbol: 'CHF',
    symbolNative: 'CHF',
    name: 'Swiss Franc',
    nameId: 'Franc Swiss',
    flag: '🇨🇭',
    countryCode: 'CH',
    decimalDigits: 2,
  ),
]);

/// Complete exhaustive list of circulating world currencies (ISO 4217).
const List<Currency> currencies = [
  Currency(
    code: 'AED',
    symbol: 'AED',
    symbolNative: 'د.إ',
    name: 'UAE Dirham',
    nameId: 'Dirham Uni Emirat Arab',
    flag: '🇦🇪',
    countryCode: 'AE',
    decimalDigits: 2,
  ),
  Currency(
    code: 'AFN',
    symbol: 'Af',
    symbolNative: '؋',
    name: 'Afghan Afghani',
    nameId: 'Afghani Afganistan',
    flag: '🇦🇫',
    countryCode: 'AF',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ALL',
    symbol: 'L',
    symbolNative: 'Lek',
    name: 'Albanian Lek',
    nameId: 'Lek Albania',
    flag: '🇦🇱',
    countryCode: 'AL',
    decimalDigits: 2,
  ),
  Currency(
    code: 'AMD',
    symbol: '֏',
    symbolNative: '֏',
    name: 'Armenian Dram',
    nameId: 'Dram Armenia',
    flag: '🇦🇲',
    countryCode: 'AM',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ANG',
    symbol: 'ƒ',
    symbolNative: 'NAƒ',
    name: 'Netherlands Antillean Guilder',
    nameId: 'Guilder Antillen Belanda',
    flag: '🇨🇼',
    countryCode: 'CW',
    decimalDigits: 2,
  ),
  Currency(
    code: 'AOA',
    symbol: 'Kz',
    symbolNative: 'Kz',
    name: 'Angolan Kwanza',
    nameId: 'Kwanza Angola',
    flag: '🇦🇴',
    countryCode: 'AO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ARS',
    symbol: r'$',
    symbolNative: r'$',
    name: 'Argentine Peso',
    nameId: 'Peso Argentina',
    flag: '🇦🇷',
    countryCode: 'AR',
    decimalDigits: 2,
  ),
  Currency(
    code: 'AUD',
    symbol: r'A$',
    symbolNative: r'$',
    name: 'Australian Dollar',
    nameId: 'Dolar Australia',
    flag: '🇦🇺',
    countryCode: 'AU',
    decimalDigits: 2,
  ),
  Currency(
    code: 'AWG',
    symbol: 'ƒ',
    symbolNative: 'Afl.',
    name: 'Aruban Florin',
    nameId: 'Florin Aruba',
    flag: '🇦🇼',
    countryCode: 'AW',
    decimalDigits: 2,
  ),
  Currency(
    code: 'AZN',
    symbol: '₼',
    symbolNative: '₼',
    name: 'Azerbaijani Manat',
    nameId: 'Manat Azerbaijan',
    flag: '🇦🇿',
    countryCode: 'AZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BAM',
    symbol: 'KM',
    symbolNative: 'KM',
    name: 'Bosnia-Herzegovina Convertible Mark',
    nameId: 'Mark Konvertibel Bosnia-Herzegovina',
    flag: '🇧🇦',
    countryCode: 'BA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BBD',
    symbol: r'Bds$',
    symbolNative: r'$',
    name: 'Barbadian Dollar',
    nameId: 'Dolar Barbados',
    flag: '🇧🇧',
    countryCode: 'BB',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BDT',
    symbol: '৳',
    symbolNative: '৳',
    name: 'Bangladeshi Taka',
    nameId: 'Taka Bangladesh',
    flag: '🇧🇩',
    countryCode: 'BD',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BGN',
    symbol: 'лв',
    symbolNative: 'лв.',
    name: 'Bulgarian Lev',
    nameId: 'Lev Bulgaria',
    flag: '🇧🇬',
    countryCode: 'BG',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BHD',
    symbol: 'BD',
    symbolNative: '.د.ب',
    name: 'Bahraini Dinar',
    nameId: 'Dinar Bahrain',
    flag: '🇧🇭',
    countryCode: 'BH',
    decimalDigits: 3,
  ),
  Currency(
    code: 'BIF',
    symbol: 'FBu',
    symbolNative: 'FBu',
    name: 'Burundian Franc',
    nameId: 'Franc Burundi',
    flag: '🇧🇮',
    countryCode: 'BI',
    decimalDigits: 0,
  ),
  Currency(
    code: 'BMD',
    symbol: r'$',
    symbolNative: r'$',
    name: 'Bermudan Dollar',
    nameId: 'Dolar Bermuda',
    flag: '🇧🇲',
    countryCode: 'BM',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BND',
    symbol: r'B$',
    symbolNative: r'$',
    name: 'Brunei Dollar',
    nameId: 'Dolar Brunei',
    flag: '🇧🇳',
    countryCode: 'BN',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BOB',
    symbol: 'Bs.',
    symbolNative: 'Bs.',
    name: 'Bolivian Boliviano',
    nameId: 'Boliviano Bolivia',
    flag: '🇧🇴',
    countryCode: 'BO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BRL',
    symbol: r'R$',
    symbolNative: r'R$',
    name: 'Brazilian Real',
    nameId: 'Real Brasil',
    flag: '🇧🇷',
    countryCode: 'BR',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BSD',
    symbol: r'B$',
    symbolNative: r'$',
    name: 'Bahamian Dollar',
    nameId: 'Dolar Bahama',
    flag: '🇧🇸',
    countryCode: 'BS',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BTN',
    symbol: 'Nu.',
    symbolNative: 'Nu.',
    name: 'Bhutanese Ngultrum',
    nameId: 'Ngultrum Bhutan',
    flag: '🇧🇹',
    countryCode: 'BT',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BWP',
    symbol: 'P',
    symbolNative: 'P',
    name: 'Botswanan Pula',
    nameId: 'Pula Botswana',
    flag: '🇧🇼',
    countryCode: 'BW',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BYN',
    symbol: 'Br',
    symbolNative: 'руб.',
    name: 'Belarusian Ruble',
    nameId: 'Ruble Belarusia',
    flag: '🇧🇾',
    countryCode: 'BY',
    decimalDigits: 2,
  ),
  Currency(
    code: 'BZD',
    symbol: r'BZ$',
    symbolNative: r'$',
    name: 'Belize Dollar',
    nameId: 'Dolar Belize',
    flag: '🇧🇿',
    countryCode: 'BZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CAD',
    symbol: r'C$',
    symbolNative: r'$',
    name: 'Canadian Dollar',
    nameId: 'Dolar Kanada',
    flag: '🇨🇦',
    countryCode: 'CA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CDF',
    symbol: 'FC',
    symbolNative: 'FC',
    name: 'Congolese Franc',
    nameId: 'Franc Kongo',
    flag: '🇨🇩',
    countryCode: 'CD',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CHF',
    symbol: 'CHF',
    symbolNative: 'CHF',
    name: 'Swiss Franc',
    nameId: 'Franc Swiss',
    flag: '🇨🇭',
    countryCode: 'CH',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CLP',
    symbol: r'$',
    symbolNative: r'$',
    name: 'Chilean Peso',
    nameId: 'Peso Chili',
    flag: '🇨🇱',
    countryCode: 'CL',
    decimalDigits: 0,
  ),
  Currency(
    code: 'CNY',
    symbol: '¥',
    symbolNative: '¥',
    name: 'Chinese Yuan',
    nameId: 'Yuan Tiongkok',
    flag: '🇨🇳',
    countryCode: 'CN',
    decimalDigits: 2,
  ),
  Currency(
    code: 'COP',
    symbol: r'$',
    symbolNative: r'$',
    name: 'Colombian Peso',
    nameId: 'Peso Kolombia',
    flag: '🇨🇴',
    countryCode: 'CO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CRC',
    symbol: '₡',
    symbolNative: '₡',
    name: 'Costa Rican Colón',
    nameId: 'Colon Kosta Rika',
    flag: '🇨🇷',
    countryCode: 'CR',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CUP',
    symbol: r'$',
    symbolNative: r'$',
    name: 'Cuban Peso',
    nameId: 'Peso Kuba',
    flag: '🇨🇺',
    countryCode: 'CU',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CVE',
    symbol: r'$',
    symbolNative: r'Esc',
    name: 'Cape Verdean Escudo',
    nameId: 'Escudo Tanjung Verde',
    flag: '🇨🇻',
    countryCode: 'CV',
    decimalDigits: 2,
  ),
  Currency(
    code: 'CZK',
    symbol: 'Kč',
    symbolNative: 'Kč',
    name: 'Czech Koruna',
    nameId: 'Koruna Ceko',
    flag: '🇨🇿',
    countryCode: 'CZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'DJF',
    symbol: 'Fdj',
    symbolNative: 'Fdj',
    name: 'Djiboutian Franc',
    nameId: 'Franc Jibuti',
    flag: '🇩🇯',
    countryCode: 'DJ',
    decimalDigits: 0,
  ),
  Currency(
    code: 'DKK',
    symbol: 'kr',
    symbolNative: 'kr.',
    name: 'Danish Krone',
    nameId: 'Krone Denmark',
    flag: '🇩🇰',
    countryCode: 'DK',
    decimalDigits: 2,
  ),
  Currency(
    code: 'DOP',
    symbol: r'RD$',
    symbolNative: r'$',
    name: 'Dominican Peso',
    nameId: 'Peso Dominika',
    flag: '🇩🇴',
    countryCode: 'DO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'DZD',
    symbol: 'DA',
    symbolNative: 'د.ج',
    name: 'Algerian Dinar',
    nameId: 'Dinar Aljazair',
    flag: '🇩🇿',
    countryCode: 'DZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'EGP',
    symbol: r'E£',
    symbolNative: 'ج.م',
    name: 'Egyptian Pound',
    nameId: 'Pound Mesir',
    flag: '🇪🇬',
    countryCode: 'EG',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ERN',
    symbol: 'Nfk',
    symbolNative: 'Nfk',
    name: 'Eritrean Nakfa',
    nameId: 'Nakfa Eritrea',
    flag: '🇪🇷',
    countryCode: 'ER',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ETB',
    symbol: 'Br',
    symbolNative: 'ብር',
    name: 'Ethiopian Birr',
    nameId: 'Birr Etiopia',
    flag: '🇪🇹',
    countryCode: 'ET',
    decimalDigits: 2,
  ),
  Currency(
    code: 'EUR',
    symbol: '€',
    symbolNative: '€',
    name: 'Euro',
    nameId: 'Euro',
    flag: '🇪🇺',
    countryCode: 'EU',
    decimalDigits: 2,
  ),
  Currency(
    code: 'FJD',
    symbol: r'FJ$',
    symbolNative: r'$',
    name: 'Fijian Dollar',
    nameId: 'Dolar Fiji',
    flag: '🇫🇯',
    countryCode: 'FJ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'FKP',
    symbol: '£',
    symbolNative: '£',
    name: 'Falkland Islands Pound',
    nameId: 'Pound Kepulauan Falkland',
    flag: '🇫🇰',
    countryCode: 'FK',
    decimalDigits: 2,
  ),
  Currency(
    code: 'GBP',
    symbol: '£',
    symbolNative: '£',
    name: 'British Pound',
    nameId: 'Pound Sterling Inggris',
    flag: '🇬🇧',
    countryCode: 'GB',
    decimalDigits: 2,
  ),
  Currency(
    code: 'GEL',
    symbol: '₾',
    symbolNative: '₾',
    name: 'Georgian Lari',
    nameId: 'Lari Georgia',
    flag: '🇬🇪',
    countryCode: 'GE',
    decimalDigits: 2,
  ),
  Currency(
    code: 'GHS',
    symbol: 'GH₵',
    symbolNative: 'GH₵',
    name: 'Ghanaian Cedi',
    nameId: 'Cedi Ghana',
    flag: '🇬🇭',
    countryCode: 'GH',
    decimalDigits: 2,
  ),
  Currency(
    code: 'GIP',
    symbol: '£',
    symbolNative: '£',
    name: 'Gibraltar Pound',
    nameId: 'Pound Gibraltar',
    flag: '🇬🇮',
    countryCode: 'GI',
    decimalDigits: 2,
  ),
  Currency(
    code: 'GMD',
    symbol: 'D',
    symbolNative: 'D',
    name: 'Gambian Dalasi',
    nameId: 'Dalasi Gambia',
    flag: '🇬🇲',
    countryCode: 'GM',
    decimalDigits: 2,
  ),
  Currency(
    code: 'GNF',
    symbol: 'FG',
    symbolNative: 'FG',
    name: 'Guinean Franc',
    nameId: 'Franc Guinea',
    flag: '🇬🇳',
    countryCode: 'GN',
    decimalDigits: 0,
  ),
  Currency(
    code: 'GTQ',
    symbol: 'Q',
    symbolNative: 'Q',
    name: 'Guatemalan Quetzal',
    nameId: 'Quetzal Guatemala',
    flag: '🇬🇹',
    countryCode: 'GT',
    decimalDigits: 2,
  ),
  Currency(
    code: 'GYD',
    symbol: r'G$',
    symbolNative: r'$',
    name: 'Guyanese Dollar',
    nameId: 'Dolar Guyana',
    flag: '🇬🇾',
    countryCode: 'GY',
    decimalDigits: 2,
  ),
  Currency(
    code: 'HKD',
    symbol: r'HK$',
    symbolNative: r'$',
    name: 'Hong Kong Dollar',
    nameId: 'Dolar Hong Kong',
    flag: '🇭🇰',
    countryCode: 'HK',
    decimalDigits: 2,
  ),
  Currency(
    code: 'HNL',
    symbol: 'L',
    symbolNative: 'L',
    name: 'Honduran Lempira',
    nameId: 'Lempira Honduras',
    flag: '🇭🇳',
    countryCode: 'HN',
    decimalDigits: 2,
  ),
  Currency(
    code: 'HTG',
    symbol: 'G',
    symbolNative: 'G',
    name: 'Haitian Gourde',
    nameId: 'Gourde Haiti',
    flag: '🇭🇹',
    countryCode: 'HT',
    decimalDigits: 2,
  ),
  Currency(
    code: 'HUF',
    symbol: 'Ft',
    symbolNative: 'Ft',
    name: 'Hungarian Forint',
    nameId: 'Forint Hungaria',
    flag: '🇭🇺',
    countryCode: 'HU',
    decimalDigits: 0,
  ),
  Currency(
    code: 'IDR',
    symbol: 'Rp',
    symbolNative: 'Rp',
    name: 'Indonesian Rupiah',
    nameId: 'Rupiah Indonesia',
    flag: '🇮🇩',
    countryCode: 'ID',
    decimalDigits: 0,
  ),
  Currency(
    code: 'ILS',
    symbol: '₪',
    symbolNative: '₪',
    name: 'Israeli New Shekel',
    nameId: 'Shekel Baru Israel',
    flag: '🇮🇱',
    countryCode: 'IL',
    decimalDigits: 2,
  ),
  Currency(
    code: 'INR',
    symbol: '₹',
    symbolNative: '₹',
    name: 'Indian Rupee',
    nameId: 'Rupee India',
    flag: '🇮🇳',
    countryCode: 'IN',
    decimalDigits: 2,
  ),
  Currency(
    code: 'IQD',
    symbol: 'IQD',
    symbolNative: 'ع.د',
    name: 'Iraqi Dinar',
    nameId: 'Dinar Irak',
    flag: '🇮🇶',
    countryCode: 'IQ',
    decimalDigits: 3,
  ),
  Currency(
    code: 'IRR',
    symbol: 'IRR',
    symbolNative: '﷼',
    name: 'Iranian Rial',
    nameId: 'Rial Iran',
    flag: '🇮🇷',
    countryCode: 'IR',
    decimalDigits: 0,
  ),
  Currency(
    code: 'ISK',
    symbol: 'kr',
    symbolNative: 'kr',
    name: 'Icelandic Króna',
    nameId: 'Krona Islandia',
    flag: '🇮🇸',
    countryCode: 'IS',
    decimalDigits: 0,
  ),
  Currency(
    code: 'JMD',
    symbol: r'J$',
    symbolNative: r'$',
    name: 'Jamaican Dollar',
    nameId: 'Dolar Jamaika',
    flag: '🇯🇲',
    countryCode: 'JM',
    decimalDigits: 2,
  ),
  Currency(
    code: 'JOD',
    symbol: 'JD',
    symbolNative: 'د.أ',
    name: 'Jordanian Dinar',
    nameId: 'Dinar Yordania',
    flag: '🇯🇴',
    countryCode: 'JO',
    decimalDigits: 3,
  ),
  Currency(
    code: 'JPY',
    symbol: '¥',
    symbolNative: '¥',
    name: 'Japanese Yen',
    nameId: 'Yen Jepang',
    flag: '🇯🇵',
    countryCode: 'JP',
    decimalDigits: 0,
  ),
  Currency(
    code: 'KES',
    symbol: 'KSh',
    symbolNative: 'KSh',
    name: 'Kenyan Shilling',
    nameId: 'Shilling Kenya',
    flag: '🇰🇪',
    countryCode: 'KE',
    decimalDigits: 2,
  ),
  Currency(
    code: 'KGS',
    symbol: 'с',
    symbolNative: 'сом',
    name: 'Kyrgystani Som',
    nameId: 'Som Kirgizstan',
    flag: '🇰🇬',
    countryCode: 'KG',
    decimalDigits: 2,
  ),
  Currency(
    code: 'KHR',
    symbol: '៛',
    symbolNative: '៛',
    name: 'Cambodian Riel',
    nameId: 'Riel Kamboja',
    flag: '🇰🇭',
    countryCode: 'KH',
    decimalDigits: 2,
  ),
  Currency(
    code: 'KMF',
    symbol: 'CF',
    symbolNative: 'CF',
    name: 'Comorian Franc',
    nameId: 'Franc Komoro',
    flag: '🇰🇲',
    countryCode: 'KM',
    decimalDigits: 0,
  ),
  Currency(
    code: 'KPW',
    symbol: '₩',
    symbolNative: '₩',
    name: 'North Korean Won',
    nameId: 'Won Korea Utara',
    flag: '🇰🇵',
    countryCode: 'KP',
    decimalDigits: 2,
  ),
  Currency(
    code: 'KRW',
    symbol: '₩',
    symbolNative: '₩',
    name: 'South Korean Won',
    nameId: 'Won Korea Selatan',
    flag: '🇰🇷',
    countryCode: 'KR',
    decimalDigits: 0,
  ),
  Currency(
    code: 'KWD',
    symbol: 'KD',
    symbolNative: 'د.ك',
    name: 'Kuwaiti Dinar',
    nameId: 'Dinar Kuwait',
    flag: '🇰🇼',
    countryCode: 'KW',
    decimalDigits: 3,
  ),
  Currency(
    code: 'KYD',
    symbol: r'CI$',
    symbolNative: r'$',
    name: 'Cayman Islands Dollar',
    nameId: 'Dolar Kepulauan Cayman',
    flag: '🇰🇾',
    countryCode: 'KY',
    decimalDigits: 2,
  ),
  Currency(
    code: 'KZT',
    symbol: '₸',
    symbolNative: '₸',
    name: 'Kazakhstani Tenge',
    nameId: 'Tenge Kazakhstan',
    flag: '🇰🇿',
    countryCode: 'KZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'LAK',
    symbol: '₭',
    symbolNative: '₭',
    name: 'Laotian Kip',
    nameId: 'Kip Laos',
    flag: '🇱🇦',
    countryCode: 'LA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'LBN',
    symbol: r'L£',
    symbolNative: 'ل.ل',
    name: 'Lebanese Pound',
    nameId: 'Pound Lebanon',
    flag: '🇱🇧',
    countryCode: 'LB',
    decimalDigits: 2,
  ),
  Currency(
    code: 'LKR',
    symbol: 'Rs',
    symbolNative: 'රු',
    name: 'Sri Lankan Rupee',
    nameId: 'Rupee Sri Lanka',
    flag: '🇱🇰',
    countryCode: 'LK',
    decimalDigits: 2,
  ),
  Currency(
    code: 'LRD',
    symbol: r'L$',
    symbolNative: r'$',
    name: 'Liberian Dollar',
    nameId: 'Dolar Liberia',
    flag: '🇱🇷',
    countryCode: 'LR',
    decimalDigits: 2,
  ),
  Currency(
    code: 'LSL',
    symbol: 'L',
    symbolNative: 'L',
    name: 'Lesotho Loti',
    nameId: 'Loti Lesotho',
    flag: '🇱🇸',
    countryCode: 'LS',
    decimalDigits: 2,
  ),
  Currency(
    code: 'LYD',
    symbol: 'LD',
    symbolNative: 'د.ل',
    name: 'Libyan Dinar',
    nameId: 'Dinar Libya',
    flag: '🇱🇾',
    countryCode: 'LY',
    decimalDigits: 3,
  ),
  Currency(
    code: 'MAD',
    symbol: 'DH',
    symbolNative: 'د.م.',
    name: 'Moroccan Dirham',
    nameId: 'Dirham Maroko',
    flag: '🇲🇦',
    countryCode: 'MA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MDL',
    symbol: 'L',
    symbolNative: 'lei',
    name: 'Moldovan Leu',
    nameId: 'Leu Moldova',
    flag: '🇲🇩',
    countryCode: 'MD',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MGA',
    symbol: 'Ar',
    symbolNative: 'Ar',
    name: 'Malagasy Ariary',
    nameId: 'Ariary Madagaskar',
    flag: '🇲🇬',
    countryCode: 'MG',
    decimalDigits: 0,
  ),
  Currency(
    code: 'MKD',
    symbol: 'ден',
    symbolNative: 'ден',
    name: 'Macedonian Denar',
    nameId: 'Denar Makedonia',
    flag: '🇲🇰',
    countryCode: 'MK',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MMK',
    symbol: 'K',
    symbolNative: 'K',
    name: 'Myanmar Kyat',
    nameId: 'Kyat Myanmar',
    flag: '🇲🇲',
    countryCode: 'MM',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MNT',
    symbol: '₮',
    symbolNative: '₮',
    name: 'Mongolian Tugrik',
    nameId: 'Tugrik Mongolia',
    flag: '🇲🇳',
    countryCode: 'MN',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MOP',
    symbol: r'MOP$',
    symbolNative: r'MOP$',
    name: 'Macanese Pataca',
    nameId: 'Pataca Makau',
    flag: '🇲🇴',
    countryCode: 'MO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MRU',
    symbol: 'UM',
    symbolNative: 'أ.م',
    name: 'Mauritanian Ouguiya',
    nameId: 'Ouguiya Mauritania',
    flag: '🇲🇷',
    countryCode: 'MR',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MUR',
    symbol: '₨',
    symbolNative: '₨',
    name: 'Mauritian Rupee',
    nameId: 'Rupee Mauritius',
    flag: '🇲🇺',
    countryCode: 'MU',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MVR',
    symbol: 'Rf',
    symbolNative: 'ރ.',
    name: 'Maldivian Rufiyaa',
    nameId: 'Rufiyaa Maladewa',
    flag: '🇲🇻',
    countryCode: 'MV',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MWK',
    symbol: 'MK',
    symbolNative: 'MK',
    name: 'Malawian Kwacha',
    nameId: 'Kwacha Malawi',
    flag: '🇲🇼',
    countryCode: 'MW',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MXN',
    symbol: r'Mex$',
    symbolNative: r'$',
    name: 'Mexican Peso',
    nameId: 'Peso Meksiko',
    flag: '🇲🇽',
    countryCode: 'MX',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MYR',
    symbol: 'RM',
    symbolNative: 'RM',
    name: 'Malaysian Ringgit',
    nameId: 'Ringgit Malaysia',
    flag: '🇲🇾',
    countryCode: 'MY',
    decimalDigits: 2,
  ),
  Currency(
    code: 'MZN',
    symbol: 'MT',
    symbolNative: 'MTn',
    name: 'Mozambican Metical',
    nameId: 'Metical Mozambik',
    flag: '🇲🇿',
    countryCode: 'MZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'NAD',
    symbol: r'N$',
    symbolNative: r'$',
    name: 'Namibian Dollar',
    nameId: 'Dolar Namibia',
    flag: '🇳🇦',
    countryCode: 'NA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'NGN',
    symbol: '₦',
    symbolNative: '₦',
    name: 'Nigerian Naira',
    nameId: 'Naira Nigeria',
    flag: '🇳🇬',
    countryCode: 'NG',
    decimalDigits: 2,
  ),
  Currency(
    code: 'NIO',
    symbol: r'C$',
    symbolNative: r'C$',
    name: 'Nicaraguan Córdoba',
    nameId: 'Cordoba Nikaragua',
    flag: '🇳🇮',
    countryCode: 'NI',
    decimalDigits: 2,
  ),
  Currency(
    code: 'NOK',
    symbol: 'kr',
    symbolNative: 'kr',
    name: 'Norwegian Krone',
    nameId: 'Krone Norwegia',
    flag: '🇳🇴',
    countryCode: 'NO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'NPR',
    symbol: 'Rs',
    symbolNative: 'रू',
    name: 'Nepalese Rupee',
    nameId: 'Rupee Nepal',
    flag: '🇳🇵',
    countryCode: 'NP',
    decimalDigits: 2,
  ),
  Currency(
    code: 'NZD',
    symbol: r'NZ$',
    symbolNative: r'$',
    name: 'New Zealand Dollar',
    nameId: 'Dolar Selandia Baru',
    flag: '🇳🇿',
    countryCode: 'NZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'OMR',
    symbol: 'OMR',
    symbolNative: 'ر.ع.',
    name: 'Omani Rial',
    nameId: 'Rial Oman',
    flag: '🇴🇲',
    countryCode: 'OM',
    decimalDigits: 3,
  ),
  Currency(
    code: 'PAB',
    symbol: 'B/.',
    symbolNative: 'B/.',
    name: 'Panamanian Balboa',
    nameId: 'Balboa Panama',
    flag: '🇵🇦',
    countryCode: 'PA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'PEN',
    symbol: 'S/',
    symbolNative: 'S/',
    name: 'Peruvian Sol',
    nameId: 'Sol Peru',
    flag: '🇵🇪',
    countryCode: 'PE',
    decimalDigits: 2,
  ),
  Currency(
    code: 'PGK',
    symbol: 'K',
    symbolNative: 'K',
    name: 'Papua New Guinean Kina',
    nameId: 'Kina Papua Nugini',
    flag: '🇵🇬',
    countryCode: 'PG',
    decimalDigits: 2,
  ),
  Currency(
    code: 'PHP',
    symbol: '₱',
    symbolNative: '₱',
    name: 'Philippine Peso',
    nameId: 'Peso Filipina',
    flag: '🇵🇭',
    countryCode: 'PH',
    decimalDigits: 2,
  ),
  Currency(
    code: 'PKR',
    symbol: 'Rs',
    symbolNative: '₨',
    name: 'Pakistani Rupee',
    nameId: 'Rupee Pakistan',
    flag: '🇵🇰',
    countryCode: 'PK',
    decimalDigits: 2,
  ),
  Currency(
    code: 'PLN',
    symbol: 'zł',
    symbolNative: 'zł',
    name: 'Polish Zloty',
    nameId: 'Zloty Polandia',
    flag: '🇵🇱',
    countryCode: 'PL',
    decimalDigits: 2,
  ),
  Currency(
    code: 'PYG',
    symbol: '₲',
    symbolNative: '₲',
    name: 'Paraguayan Guarani',
    nameId: 'Guarani Paraguay',
    flag: '🇵🇾',
    countryCode: 'PY',
    decimalDigits: 0,
  ),
  Currency(
    code: 'QAR',
    symbol: 'QR',
    symbolNative: 'ر.ق',
    name: 'Qatari Riyal',
    nameId: 'Riyal Qatar',
    flag: '🇶🇦',
    countryCode: 'QA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'RON',
    symbol: 'lei',
    symbolNative: 'lei',
    name: 'Romanian Leu',
    nameId: 'Leu Rumania',
    flag: '🇷🇴',
    countryCode: 'RO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'RSD',
    symbol: 'din.',
    symbolNative: 'дин.',
    name: 'Serbian Dinar',
    nameId: 'Dinar Serbia',
    flag: '🇷🇸',
    countryCode: 'RS',
    decimalDigits: 2,
  ),
  Currency(
    code: 'RUB',
    symbol: '₽',
    symbolNative: '₽',
    name: 'Russian Ruble',
    nameId: 'Ruble Rusia',
    flag: '🇷🇺',
    countryCode: 'RU',
    decimalDigits: 2,
  ),
  Currency(
    code: 'RWF',
    symbol: 'RF',
    symbolNative: 'RF',
    name: 'Rwandan Franc',
    nameId: 'Franc Rwanda',
    flag: '🇷🇼',
    countryCode: 'RW',
    decimalDigits: 0,
  ),
  Currency(
    code: 'SAR',
    symbol: 'SAR',
    symbolNative: '﷼',
    name: 'Saudi Riyal',
    nameId: 'Riyal Arab Saudi',
    flag: '🇸🇦',
    countryCode: 'SA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SBD',
    symbol: r'SI$',
    symbolNative: r'$',
    name: 'Solomon Islands Dollar',
    nameId: 'Dolar Kepulauan Solomon',
    flag: '🇸🇧',
    countryCode: 'SB',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SCR',
    symbol: 'SR',
    symbolNative: 'SR',
    name: 'Seychellois Rupee',
    nameId: 'Rupee Seychelles',
    flag: '🇸🇨',
    countryCode: 'SC',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SDG',
    symbol: 'SDG',
    symbolNative: 'ج.س.',
    name: 'Sudanese Pound',
    nameId: 'Pound Sudan',
    flag: '🇸🇩',
    countryCode: 'SD',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SEK',
    symbol: 'kr',
    symbolNative: 'kr',
    name: 'Swedish Krona',
    nameId: 'Krona Swedia',
    flag: '🇸🇪',
    countryCode: 'SE',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SGD',
    symbol: r'S$',
    symbolNative: r'$',
    name: 'Singapore Dollar',
    nameId: 'Dolar Singapura',
    flag: '🇸🇬',
    countryCode: 'SG',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SHP',
    symbol: '£',
    symbolNative: '£',
    name: 'Saint Helena Pound',
    nameId: 'Pound Saint Helena',
    flag: '🇸🇭',
    countryCode: 'SH',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SLE',
    symbol: 'Le',
    symbolNative: 'Le',
    name: 'Sierra Leonean Leone',
    nameId: 'Leone Sierra Leone',
    flag: '🇸🇱',
    countryCode: 'SL',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SOS',
    symbol: 'S',
    symbolNative: 'S',
    name: 'Somali Shilling',
    nameId: 'Shilling Somalia',
    flag: '🇸🇴',
    countryCode: 'SO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SRD',
    symbol: r'Sr$',
    symbolNative: r'$',
    name: 'Surinamese Dollar',
    nameId: 'Dolar Suriname',
    flag: '🇸🇷',
    countryCode: 'SR',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SSP',
    symbol: '£',
    symbolNative: '£',
    name: 'South Sudanese Pound',
    nameId: 'Pound Sudan Selatan',
    flag: '🇸🇸',
    countryCode: 'SS',
    decimalDigits: 2,
  ),
  Currency(
    code: 'STN',
    symbol: 'Db',
    symbolNative: 'Db',
    name: 'São Tomé & Príncipe Dobra',
    nameId: 'Dobra Sao Tome dan Principe',
    flag: '🇸🇹',
    countryCode: 'ST',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SVC',
    symbol: '₡',
    symbolNative: '₡',
    name: 'Salvadoran Colón',
    nameId: 'Colon El Salvador',
    flag: '🇸🇻',
    countryCode: 'SV',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SYP',
    symbol: r'£S',
    symbolNative: 'ل.س',
    name: 'Syrian Pound',
    nameId: 'Pound Suriah',
    flag: '🇸🇾',
    countryCode: 'SY',
    decimalDigits: 2,
  ),
  Currency(
    code: 'SZL',
    symbol: 'E',
    symbolNative: 'E',
    name: 'Swazi Lilangeni',
    nameId: 'Lilangeni Eswatini',
    flag: '🇸🇿',
    countryCode: 'SZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'THB',
    symbol: '฿',
    symbolNative: '฿',
    name: 'Thai Baht',
    nameId: 'Baht Thailand',
    flag: '🇹🇭',
    countryCode: 'TH',
    decimalDigits: 2,
  ),
  Currency(
    code: 'TJS',
    symbol: 'SM',
    symbolNative: 'смн.',
    name: 'Tajikistani Somoni',
    nameId: 'Somoni Tajikistan',
    flag: '🇹🇯',
    countryCode: 'TJ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'TMT',
    symbol: 'T',
    symbolNative: 'T',
    name: 'Turkmenistani Manat',
    nameId: 'Manat Turkmenistan',
    flag: '🇹🇲',
    countryCode: 'TM',
    decimalDigits: 2,
  ),
  Currency(
    code: 'TND',
    symbol: 'DT',
    symbolNative: 'د.ت',
    name: 'Tunisian Dinar',
    nameId: 'Dinar Tunisia',
    flag: '🇹🇳',
    countryCode: 'TN',
    decimalDigits: 3,
  ),
  Currency(
    code: 'TOP',
    symbol: r'T$',
    symbolNative: r'T$',
    name: 'Tongan Paʻanga',
    nameId: 'Paanga Tonga',
    flag: '🇹🇴',
    countryCode: 'TO',
    decimalDigits: 2,
  ),
  Currency(
    code: 'TRY',
    symbol: '₺',
    symbolNative: '₺',
    name: 'Turkish Lira',
    nameId: 'Lira Turki',
    flag: '🇹🇷',
    countryCode: 'TR',
    decimalDigits: 2,
  ),
  Currency(
    code: 'TTD',
    symbol: r'TT$',
    symbolNative: r'$',
    name: 'Trinidad & Tobago Dollar',
    nameId: 'Dolar Trinidad dan Tobago',
    flag: '🇹🇹',
    countryCode: 'TT',
    decimalDigits: 2,
  ),
  Currency(
    code: 'TWD',
    symbol: r'NT$',
    symbolNative: r'NT$',
    name: 'New Taiwan Dollar',
    nameId: 'Dolar Taiwan Baru',
    flag: '🇹🇼',
    countryCode: 'TW',
    decimalDigits: 2,
  ),
  Currency(
    code: 'TZS',
    symbol: 'TSh',
    symbolNative: 'TSh',
    name: 'Tanzanian Shilling',
    nameId: 'Shilling Tanzania',
    flag: '🇹🇿',
    countryCode: 'TZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'UAH',
    symbol: '₴',
    symbolNative: '₴',
    name: 'Ukrainian Hryvnia',
    nameId: 'Hryvnia Ukraina',
    flag: '🇺🇦',
    countryCode: 'UA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'UGX',
    symbol: 'USh',
    symbolNative: 'USh',
    name: 'Ugandan Shilling',
    nameId: 'Shilling Uganda',
    flag: '🇺🇬',
    countryCode: 'UG',
    decimalDigits: 0,
  ),
  Currency(
    code: 'USD',
    symbol: r'$',
    symbolNative: r'$',
    name: 'US Dollar',
    nameId: 'Dolar Amerika Serikat',
    flag: '🇺🇸',
    countryCode: 'US',
    decimalDigits: 2,
  ),
  Currency(
    code: 'UYU',
    symbol: r'$U',
    symbolNative: r'$',
    name: 'Uruguayan Peso',
    nameId: 'Peso Uruguay',
    flag: '🇺🇾',
    countryCode: 'UY',
    decimalDigits: 2,
  ),
  Currency(
    code: 'UZS',
    symbol: "so'm",
    symbolNative: "сўм",
    name: 'Uzbekistani Som',
    nameId: 'Som Uzbekistan',
    flag: '🇺🇿',
    countryCode: 'UZ',
    decimalDigits: 2,
  ),
  Currency(
    code: 'VES',
    symbol: 'Bs.',
    symbolNative: 'Bs.',
    name: 'Venezuelan Bolívar',
    nameId: 'Bolivar Venezuela',
    flag: '🇻🇪',
    countryCode: 'VE',
    decimalDigits: 2,
  ),
  Currency(
    code: 'VND',
    symbol: '₫',
    symbolNative: '₫',
    name: 'Vietnamese Dong',
    nameId: 'Dong Vietnam',
    flag: '🇻🇳',
    countryCode: 'VN',
    decimalDigits: 0,
  ),
  Currency(
    code: 'VUV',
    symbol: 'VT',
    symbolNative: 'VT',
    name: 'Vanuatu Vatu',
    nameId: 'Vatu Vanuatu',
    flag: '🇻🇺',
    countryCode: 'VU',
    decimalDigits: 0,
  ),
  Currency(
    code: 'WST',
    symbol: r'WS$',
    symbolNative: r'T',
    name: 'Samoan Tala',
    nameId: 'Tala Samoa',
    flag: '🇼🇸',
    countryCode: 'WS',
    decimalDigits: 2,
  ),
  Currency(
    code: 'XAF',
    symbol: 'FCFA',
    symbolNative: 'FCFA',
    name: 'Central African CFA Franc',
    nameId: 'Franc CFA Afrika Tengah',
    flag: '🇨🇲',
    countryCode: 'CM',
    decimalDigits: 0,
  ),
  Currency(
    code: 'XCD',
    symbol: r'EC$',
    symbolNative: r'$',
    name: 'East Caribbean Dollar',
    nameId: 'Dolar Karibia Timur',
    flag: '🇦🇬',
    countryCode: 'AG',
    decimalDigits: 2,
  ),
  Currency(
    code: 'XOF',
    symbol: 'CFA',
    symbolNative: 'CFA',
    name: 'West African CFA Franc',
    nameId: 'Franc CFA Afrika Barat',
    flag: '🇨🇮',
    countryCode: 'CI',
    decimalDigits: 0,
  ),
  Currency(
    code: 'XPF',
    symbol: '₣',
    symbolNative: '₣',
    name: 'CFP Franc',
    nameId: 'Franc CFP Pasifik',
    flag: '🇵🇫',
    countryCode: 'PF',
    decimalDigits: 0,
  ),
  Currency(
    code: 'YER',
    symbol: 'YER',
    symbolNative: '﷼',
    name: 'Yemeni Rial',
    nameId: 'Rial Yaman',
    flag: '🇾🇪',
    countryCode: 'YE',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ZAR',
    symbol: 'R',
    symbolNative: 'R',
    name: 'South African Rand',
    nameId: 'Rand Afrika Selatan',
    flag: '🇿🇦',
    countryCode: 'ZA',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ZMW',
    symbol: 'ZK',
    symbolNative: 'ZK',
    name: 'Zambian Kwacha',
    nameId: 'Kwacha Zambia',
    flag: '🇿🇲',
    countryCode: 'ZM',
    decimalDigits: 2,
  ),
  Currency(
    code: 'ZWG',
    symbol: 'ZiG',
    symbolNative: 'ZiG',
    name: 'Zimbabwe Gold',
    nameId: 'Emas Zimbabwe',
    flag: '🇿🇼',
    countryCode: 'ZW',
    decimalDigits: 2,
  ),
];

/// Fast O(1) map indexed by uppercase ISO 4217 currency code.
final Map<String, Currency> _currencyMapByCode = {
  for (final c in currencies) c.code: c,
};

/// Public map of all currencies indexed by uppercase 3-letter currency code.
final Map<String, Currency> currencyMapByCode =
    Map.unmodifiable(_currencyMapByCode);

/// Search currencies matching code, name, or symbol.
List<Currency> searchCurrencies(String query) {
  final clean = query.trim().toLowerCase();
  if (clean.isEmpty) return currencies;

  return currencies.where((c) {
    return c.code.toLowerCase().contains(clean) ||
        c.symbol.toLowerCase().contains(clean) ||
        c.name.toLowerCase().contains(clean) ||
        c.nameId.toLowerCase().contains(clean) ||
        c.countryCode.toLowerCase().contains(clean);
  }).toList();
}
